[package]
name = "sftptest"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
env_logger = "0.11.8"
log = "0.4.28"
russh = {version = "0.54.6", features = ["ring"], default-features = false}
russh-sftp = "2.1.1"
tokio = {version = "1.48.0", features = ["fs"]}
